### PR TITLE
initial version of bdd.yml file

### PR DESCRIPTION
**Pull request by cdaid**
Created bdd.yml

### CODE REVIEW

**Comment by yitao-zhou** [comment]
Hopefully, I have fixed this

**Comment by yitao-zhou** [comment]
This one does not seem to have a story associated?

**Comment by cdaid** [comment]
> This one does not seem to have a story associated?

@yitao-zhou I just connected this issue to the story, #40 Create GitHub Actions Workflow File for BDD

**Review by yitao-zhou — APPROVED** [review]
Believe this one can be merged.

**Pull request merged**
