### PR TITLE
add feature and step files

### LINKED ISSUE #39: [4] Create BDD .feature file and accompany steps.py file to test RESTful API from outside in
**As a** [developer]
**I need** [to create  BDD .feature file and accompany steps.py file]  
**So that** [I can ensure that my API functions correctly and meets user requirements]  
   
 ### Details and Assumptions

* Define the user requirements for the RESTful API, including the expected functionality and user experience.
* Write a BDD .feature file that outlines the behavior of the RESTful API in a user-friendly language.
* Define the steps for testing the RESTful API in the steps.py file, using a tool such as Behave or Pytest-BDD.
* Implement the API endpoints and ensure that they meet the user requirements outlined in the BDD .feature file.
* Run the tests using the steps.py file to verify that the API functions as expected and meets the user requirements.
* Refactor the API code as necessary based on the test results and user feedback.
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given [a user reqirement]
 When [I test the RESTful API]
 Then [it meets the user requirements outlined in the BDD .feature file.]
```

### PR DESCRIPTION
**Pull request by Pimnipalmie**

### CODE REVIEW

**Comment by Pimnipalmie** [comment]
Test failed because we haven't done issue #40 Create GitHub Actions Workflow File for BDD

**Comment by cdaid** [comment]
Will hop on #40 to help remove this blocker!

**Comment by yitao-zhou** [comment]
Error fixed by merging from Master. Hope it helps!

**Comment by Pimnipalmie** [comment]
Wow that works! @yitao-zhou could you help merge this pull request? Thank u :)

**Comment by yitao-zhou** [comment]
> Wow that works! @yitao-zhou could you help merge this pull request? Thank u :)

Merged!

**Pull request merged**
