### PR TITLE
initial version of UI

### PR DESCRIPTION
**Pull request by yitao-zhou**
Let's try to test if all the functionality of this will work. If some function goes out of control, please let me know!

Please switch to this branch, then command with `flask run`, and go to [http://127.0.0.1:8000](url), try to see if all the functions work properly by testing extensively. 

You may see a lot of wrong words, like pets showing around, please track where this happens.

### CODE REVIEW

**Comment by Pimnipalmie** [comment]
@yitao-zhou One basic question, Do I have to run anything before flash run? I got the response command not found TT

**Comment by yitao-zhou** [comment]
> @yitao-zhou One basic question, Do I have to run anything before flash run? I got the response command not found TT

@Pimnipalmie I don't think so... Are you in docker environment?

**Comment by Pimnipalmie** [comment]
Yeah I'm in docker env. Maybe something is wrong on my side, sometimes things are not loaded correctly. Someone else can try it out if that works

**Comment by gothmother** [comment]
Tested this (manually in lieu of fully functioning BDD). After merging I will start adding test cases.

**Pull request merged**
